UI/RentaTransport.AdminUI/Controllers/BrandController.cs
using RentaTransport.AdminUI.Controllers.BaseControllers;
using RentaTransport.AdminUI.Models;
using RentaTransport.AdminUI.ServiceFacade;
using RentaTransport.BLL.DTOs;
using RentaTransport.BLL.Repositories;
using RentaTransport.BLL.Services;
using RentaTransport.BLL.Validators;

namespace RentaTransport.AdminUI.Controllers
{
    public class BrandController : CrudController<BrandViewModel,BrandServiceFacade,BrandDTO,IBrandRepository,BrandValidator,BrandService>
    {
        public BrandController(BrandServiceFacade brandServiceFacade):base(brandServiceFacade)
        {
        }
    }
}

UI/RentaTransport.AdminUI/Controllers/CityController.cs
using RentaTransport.AdminUI.Controllers.BaseControllers;
using RentaTransport.AdminUI.Models;
using RentaTransport.AdminUI.ServiceFacade;
using RentaTransport.BLL.DTOs;
using RentaTransport.BLL.Repositories;
using RentaTransport.BLL.Services;
using RentaTransport.BLL.Validators;

namespace RentaTransport.AdminUI.Controllers
{
    public class CityController : CrudController<CityViewModel, CityServiceFacade, CityDTO, ICityRepository, CityValidator,CityService>
    {
        public CityController(CityServiceFacade cityServiceFacade):base(cityServiceFacade)
        {
        }

    }
}

UI/RentaTransport.AdminUI/Controllers/ColorController.cs
using RentaTransport.AdminUI.Controllers.BaseControllers;
using RentaTransport.AdminUI.Models;
using RentaTransport.AdminUI.ServiceFacade;
using RentaTransport.BLL.DTOs;
using RentaTransport.BLL.Repositories;
using RentaTransport.BLL.Services;
using RentaTransport.BLL.Validators;

namespace RentaTransport.AdminUI.Controllers
{
    public class ColorController : CrudController<ColorViewModel, ColorServiceFacade, ColorDTO, IColorRepository, ColorValidator, ColorService>
    {
        public ColorController(ColorServiceFacade colorService):base(colorService)
        {
        }
    }
}

UI/RentaTransport.AdminUI/Controllers/ModelController.cs
using RentaTransport.AdminUI.Controllers.BaseControllers;
using RentaTransport.AdminUI.Models;
using RentaTransport.AdminUI.ServiceFacade;
using RentaTransport.BLL.DTOs;
using RentaTransport.BLL.Repositories;
using RentaTransport.BLL.Services;
using RentaTransport.BLL.Validators;
namespace RentaTransport.AdminUI.Controllers
{
    public class ModelController : CrudController<ModelViewModel,ModelServiceFacade,ModelDTO,IModelRepository,ModelValidator,ModelService>
    {
        public ModelController(ModelServiceFacade modelServiceFacade):base(modelServiceFacade)
        {
        }
    }
}

UI/RentaTransport.AdminUI/Views/Shared/TemplatePartials/_CardHeaderPartial.cshtml
<div class="card-header header-elements-inline">
    <h3 class="card-title">
        @ViewData["FormName"]
    </h3>
    <div class="header-elements">
        <div class="list-icons">
            <a class="list-icons-item" data-action="collapse"></a>
            <a class="list-icons-item" data-action="remove"></a>
        </div>
    </div>
</div>

UI/RentaTransport.AdminUI/Views/Shared/TemplatePartials/_FooterPartial.cshtml
<div class="navbar navbar-expand-lg navbar-light">
    <div class="text-center d-lg-none w-100">
        <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
            <i class="icon-unfold mr-2"></i>
            Footer
        </button>
    </div>

    <div class="navbar-collapse collapse" id="navbar-footer">
        <span class="navbar-text">
            &copy;@DateTime.Now.Year <a href="#">Rent a Transport  <b>by Team</b></a>
        </span>
    </div>
</div>

UI/RentaTransport.AdminUI/Views/Shared/TemplatePartials/_HeaderPartial.cshtml
<header>
    <div class="navbar navbar-expand-md navbar-dark bg-indigo navbar-static">
        <div class="navbar-brand">
            <a href="index.html" class="d-inline-block">
                <img src="~/img/logo_light.png" alt="">
            </a>
        </div>

        <div class="d-md-none">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
                <i class="icon-tree5"></i>
            </button>
            <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
                <i class="icon-paragraph-justify3"></i>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar-mobile">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
                        <i class="icon-paragraph-justify3"></i>
                    </a>
                </li>
            </ul>

            <span class="navbar-text ml-md-3">
                <span class="badge badge-mark border-orange-300 mr-2"></span>
                Good @DateTime.Now.DayOfWeek, Mr/Mrs
            </span>

            <ul class="navbar-nav ml-md-auto">
                <li class="nav-item dropdown">
                    <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-make-group mr-2"></i>
                        Connect
                    </a>

                    <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                        <div class="dropdown-content-body p-2">
                            <div class="row no-gutters">
                                <div class="col-12 col-sm-4">
                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-github4 icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Github</div>
                                    </a>

                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-dropbox text-blue-400 icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Dropbox</div>
                                    </a>
                                </div>

                                <div class="col-12 col-sm-4">
                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-dribbble3 text-pink-400 icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Dribbble</div>
                                    </a>

                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-google-drive text-success-400 icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Drive</div>
                                    </a>
                                </div>

                                <div class="col-12 col-sm-4">
                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-twitter text-info-400 icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Twitter</div>
                                    </a>

                                    <a href="#" class="d-block text-default text-center ripple-dark rounded p-3">
                                        <i class="icon-youtube text-danger icon-2x"></i>
                                        <div class="font-size-sm font-weight-semibold text-uppercase mt-2">Youtube</div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-pulse2 mr-2"></i>
                        Activity
                    </a>

                    <div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
                        <div class="dropdown-content-header">
                            <span class="font-size-sm line-height-sm text-uppercase font-weight-semibold">Latest activity</span>
                            <a href="#" class="text-default"><i class="icon-search4 font-size-base"></i></a>
                        </div>

                        <div class="dropdown-content-body dropdown-scrollable">
                            <ul class="media-list">
                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-success-400 rounded-round btn-icon"><i class="icon-mention"></i></a>
                                    </div>

                                    <div class="media-body">
                                        <a href="#">Taylor Swift</a> mentioned you in a post "Angular JS. Tips and tricks"
                                        <div class="font-size-sm text-muted mt-1">4 minutes ago</div>
                                    </div>
                                </li>

                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-pink-400 rounded-round btn-icon"><i class="icon-paperplane"></i></a>
                                    </div>

                                    <div class="media-body">
                                        Special offers have been sent to subscribed users by <a href="#">Donna Gordon</a>
                                        <div class="font-size-sm text-muted mt-1">36 minutes ago</div>
                                    </div>
                                </li>

                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-blue rounded-round btn-icon"><i class="icon-plus3"></i></a>
                                    </div>

                                    <div class="media-body">
                                        <a href="#">Chris Arney</a> created a new <span class="font-weight-semibold">Design</span> branch in <span class="font-weight-semibold">Limitless</span> repository
                                        <div class="font-size-sm text-muted mt-1">2 hours ago</div>
                                    </div>
                                </li>

                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-purple-300 rounded-round btn-icon"><i class="icon-truck"></i></a>
                                    </div>

                                    <div class="media-body">
                                        Shipping cost to the Netherlands has been reduced, database updated
                                        <div class="font-size-sm text-muted mt-1">Feb 8, 11:30</div>
                                    </div>
                                </li>

                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-warning-400 rounded-round btn-icon"><i class="icon-comment"></i></a>
                                    </div>

                                    <div class="media-body">
                                        New review received on <a href="#">Server side integration</a> services
                                        <div class="font-size-sm text-muted mt-1">Feb 2, 10:20</div>
                                    </div>
                                </li>

                                <li class="media">
                                    <div class="mr-3">
                                        <a href="#" class="btn bg-teal-400 rounded-round btn-icon"><i class="icon-spinner11"></i></a>
                                    </div>

                                    <div class="media-body">
                                        <strong>January, 2018</strong> - 1320 new users, 3284 orders, $49,390 revenue
                                        <div class="font-size-sm text-muted mt-1">Feb 1, 05:46</div>
                                    </div>
                                </li>
                            </ul>
                        </div>

                        <div class="dropdown-content-footer bg-light">
                            <a href="#" class="font-size-sm line-height-sm text-uppercase font-weight-semibold text-grey mr-auto">All activity</a>
                            <div>
                                <a href="#" class="text-grey" data-popup="tooltip" title="Clear list"><i class="icon-checkmark3"></i></a>
                                <a href="#" class="text-grey ml-2" data-popup="tooltip" title="Settings"><i class="icon-gear"></i></a>
                            </div>
                        </div>
                    </div>
                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Logout", "Admin")" class="navbar-nav-link">
                        <i class="icon-switch2"></i>
                        <span class="d-md-none ml-2">Logout</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</header>

UI/RentaTransport.AdminUI/Views/Shared/TemplatePartials/_PageHeaderPartial.cshtml
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Home</span> - Dashboard</h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        <div class="header-elements d-none">
            <div class="d-flex justify-content-center">
                <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                    <i class="icon-bars-alt text-pink-300"></i>
                    <span>Statistics</span>
                </a>
                <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                    <i class="icon-calculator text-pink-300"></i>
                    <span>Invoices</span>
                </a>
                <a href="#" class="btn btn-link btn-float font-size-sm font-weight-semibold text-default">
                    <i class="icon-calendar5 text-pink-300"></i>
                    <span>Schedule</span>
                </a>
            </div>
        </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="index.html" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <span class="breadcrumb-item active">Dashboard</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>

        <div class="header-elements d-none">
            <div class="breadcrumb justify-content-center">
                <a href="#" class="breadcrumb-elements-item">
                    <i class="icon-comment-discussion mr-2"></i>
                    Support
                </a>

                <div class="breadcrumb-elements-item dropdown p-0">
                    <a href="#" class="breadcrumb-elements-item dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-gear mr-2"></i>
                        Settings
                    </a>

                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="#" class="dropdown-item"><i class="icon-user-lock"></i> Account security</a>
                        <a href="#" class="dropdown-item"><i class="icon-statistics"></i> Analytics</a>
                        <a href="#" class="dropdown-item"><i class="icon-accessibility"></i> Accessibility</a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item"><i class="icon-gear"></i> All settings</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

UI/RentaTransport.AdminUI/Views/Shared/TemplatePartials/_RemoveModalPartial.cshtml
@using RentaTransport.Common.Resources

<form method="POST" data-ajax="true" id="removeForm">
    @Html.AntiForgeryToken()
    <div class="modal" id="removeModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">@UI.Attention</h5>
                </div>
                <div class="modal-body">
                    @UI.AreYouSureRemoveData
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-primary" onclick="OnRemoveModalConfirm()">
                        @UI.Confirm
                    </button>
                    <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">
                        @UI.Cancel
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>

UI/RentaTransport.AdminUI/Views/Shared/TemplatePartials/_SidebarMenuPartial.cshtml
<div class="card card-sidebar-mobile">
    <ul class="nav nav-sidebar" data-nav-type="accordion">
        <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">Main</div> <i class="icon-menu" title="Main"></i></li>
        <li class="nav-item">
            <a href="#" class="nav-link active">
                <i class="icon-home4"></i>
                <span>
                    Dashboard
                </span>
            </a>
        </li>
        <li class="nav-item nav-item-submenu">
            <a href="#" class="nav-link"><i class="icon-copy"></i> <span>Cars</span></a>
            <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                <li class="nav-item"><a href=@Url.Action("Index","Brand") class="nav-link">Brands</a></li>
                <li class="nav-item"><a href=@Url.Action("Index","Model") class="nav-link">Models</a></li>
                <li class="nav-item"><a href=@Url.Action("Index", "City") class="nav-link">Cities</a></li>
                <li class="nav-item"><a href=@Url.Action("Index","FuelType") class="nav-link">Fuel Types</a></li>
                <li class="nav-item"><a href=@Url.Action("Index","CarAddition") class="nav-link">Car Additions</a></li>
                <li class="nav-item"><a href=@Url.Action("Index","BanType") class="nav-link">Ban Types</a></li>
                <li class="nav-item"><a href=@Url.Action("Index","Color") class="nav-link">Colors</a></li>
            </ul>
        </li>

        <li class="nav-item nav-item-submenu">
            <a href="#" class="nav-link"><i class="icon-copy"></i> <span>Customers</span></a>
            <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                <li class="nav-item"><a href=@Url.Action("Index", "Customer") class="nav-link">Customers</a></li>
            </ul>
        </li>

        <li class="nav-item nav-item-submenu">
            <a href="#" class="nav-link"><i class="icon-copy"></i> <span>Price Plans</span></a>
            <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                <li class="nav-item"><a href=@Url.Action("Index", "PricePlan") class="nav-link">Price Plans</a></li>
            </ul>
            <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                <li class="nav-item"><a href=@Url.Action("Index", "Frequency") class="nav-link">Frequencies</a></li>
            </ul>
            <ul class="nav nav-group-sub" data-submenu-title="Layouts">
                <li class="nav-item"><a href=@Url.Action("Index", "PricePlanHistory") class="nav-link">Price Plan Histories</a></li>
            </ul>
        </li>
    </ul>
</div>

UI/RentaTransport.AdminUI/Views/Shared/TemplatePartials/_SidebarPartial.cshtml
<div class="sidebar sidebar-light sidebar-main sidebar-expand-md">
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        <span class="font-weight-semibold">Navigation</span>
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>
    <div class="sidebar-content">
        @await Html.PartialAsync("TemplatePartials/_SidebarUserPartial")
        @await Html.PartialAsync("TemplatePartials/_SidebarMenuPartial")
    </div>
</div>

UI/RentaTransport.AdminUI/Views/Shared/TemplatePartials/_SidebarUserPartial.cshtml
<div class="sidebar-user-material">
    <div class="sidebar-user-material-body">
        <div class="card-body text-center">
            <a href="#">
                <img src="~/img/demo/users/picture2.jpg" class="img-fluid rounded-circle shadow-1 mb-3" width="80" height="80" alt="">
            </a>
            <h6 class="mb-0 text-white text-shadow-dark">Admin</h6>
            <span class="font-size-sm text-white text-shadow-dark">Paris, France</span>
        </div>

        <div class="sidebar-user-material-footer">
            <a href="#user-nav" class="d-flex justify-content-between align-items-center text-shadow-dark dropdown-toggle legitRipple" data-toggle="collapse"><span>My account</span></a>
        </div>
    </div>

    <div class="collapse" id="user-nav">
        <ul class="nav nav-sidebar">
            <li class="nav-item">
                <a href="#" class="nav-link legitRipple">
                    <i class="icon-user-plus"></i>
                    <span>My profile</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link legitRipple">
                    <i class="icon-coins"></i>
                    <span>My balance</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link legitRipple">
                    <i class="icon-comment-discussion"></i>
                    <span>Messages</span>
                    <span class="badge bg-teal-400 badge-pill align-self-center ml-auto">58</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link legitRipple">
                    <i class="icon-cog5"></i>
                    <span>Account settings</span>
                </a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link legitRipple">
                    <i class="icon-switch2"></i>
                    <span>Logout</span>
                </a>
            </li>
        </ul>
    </div>
</div>