UI/RentaTransport.AdminUI/Controllers/FuelTypeController.cs
using RentaTransport.AdminUI.Controllers.BaseControllers;
using RentaTransport.AdminUI.Models;
using RentaTransport.AdminUI.ServiceFacade;
using RentaTransport.BLL.DTOs;
using RentaTransport.BLL.Repositories;
using RentaTransport.BLL.Services;
using RentaTransport.BLL.Validators;

namespace RentaTransport.AdminUI.Controllers
{
    public class FuelTypeController : CrudController<FuelViewModel,FuelServiceFacade,FuelTypeDTO,IFuelTypeRepository,FuelTypeValidator,FuelTypeService>
    {
        public FuelTypeController(FuelServiceFacade fuelServiceFacade):base(fuelServiceFacade)
        {
        }
    }
}

UI/RentaTransport.AdminUI/Views/FuelType/Form.cshtml
@model RentaTransport.AdminUI.Models.FuelViewModel

<div class="card">
    <div class="card-body">
        <form asp-controller="FuelType" asp-action="Save"
              data-ajax="true" data-ajax-method="post" data-ajax-success="OnSuccess"
              data-ajax-failure="OnFailure" data-ajax-begin="OnLoading">

            @Html.AntiForgeryToken()
            <input asp-for="Id" type="hidden" />
            <input asp-for="Status" type="hidden" />

            <div class="col-sm-6 col-md-6 col-lg-6 col-xl-6">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input type="text" asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12">
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
            </div>

            <div class="d-flex justify-content-start align-items-center">
                <partial name="TemplatePartials/_FormButtonsPartial" />
            </div>
        </form>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        function OnSuccess(response) {
            if (response.IsSucceed) {
                location.href = '@Url.Action("Index", "FuelType")';
                $("#loading").css('display', 'none');
            }
            else {
                $("#loading").css('display', 'none');
                $(':input[type="submit"]').prop('disabled', false);
                alertify.error(response.Description);
            }
        }

    </script>

}

UI/RentaTransport.AdminUI/Views/FuelType/Index.cshtml
@using RentaTransport.Common.Resources

<div class="card">
    <div class="card-header header-elements-inline">
        <div class="header-elements">
            <a class="btn bg-teal-400 btn-labeled btn-labeled-left legitRipple" asp-controller="FuelType" asp-action="Form">
                <b><i class="icon-plus-circle2"></i></b> @UI.Create
            </a>
        </div>
    </div>
    <div class="card-body">
        <partial name="_GridPartial" />
    </div>
</div>

UI/RentaTransport.AdminUI/Views/FuelType/_GridPartial.cshtml
@using RentaTransport.Common.Resources

@(Html.DevExtreme().DataGrid<RentaTransport.BLL.DTOs.FuelTypeDTO>()
            .ID("usersGridContainer")
            .DataSource(d => d.Mvc().Controller("FuelType").LoadAction("Data").Key("Id"))
            .RemoteOperations(false)
            .AllowColumnReordering(true)
            .RowAlternationEnabled(true)
            .FilterRow(filterRow => filterRow.Visible(true).ApplyFilter(GridApplyFilterMode.Auto))
            .ShowBorders(true)
            .Paging(p => p.PageSize(10))
            .Pager(p => p.ShowPageSizeSelector(true).AllowedPageSizes(new int[] { 10, 20, 50 }))
            //.SearchPanel(s => s.Visible(true).HighlightCaseSensitive(true))
            .Scrolling(scrolling => scrolling.Mode(GridScrollingMode.Standard))
            //.Export(e => e.Enabled(true).FileName($"UserRolesGrid-{DateTime.Now.ToString()}"))
            .ColumnMinWidth(120)
            //.HeaderFilter(headerFilter => headerFilter.Visible(true))
            .Columns(columns =>
            {

                columns.AddFor(m => m.Name)
                    .Caption(UI.Name);

                columns.AddFor(m => m.Description)
                    .Caption(UI.Description);

                columns.AddFor(m => m.CreatedDate)
                   .Caption(UI.CreatedDate);

                columns.AddFor(m => m.Id)
                    .Caption(UI.Operations)
                    .Width(50)
                    .AllowFiltering(false)
                    .AllowSorting(false)
                    .CellTemplate(@<text>
                        <a class="btn bg-teal-400 btn-icon legitRipple" onclick="HrefMe('@Url.Action("Form", "FuelType")', '<%=value%>')">
                            <i class="icon-pencil4"></i>
                        </a>
                        <a class="btn bg-danger btn-icon legitRipple" onclick="ShowRemoveModal('@Url.Action("Remove", "FuelType")', '<%=value%>')">
                            <i class="icon-trash"></i>
                        </a>
                    </text>);
                            })
)